---
driver:
  name: terraform
  root_module_directory: examples/ebs_optimized_test_fixture

provisioner:
  name: terraform

platforms:
- name: aws

verifier:
  name: terraform

suites:
  -
    name: default
    verifier:
      groups:
        -
          name: default
          attributes:
            supported: supported
            unsupported: unsupported
            unknown_type_result: unknown
            ebs_optimized_instance_id: ebs_optimized_instance_id
            not_ebs_optimized_instance_id: not_ebs_optimized_instance_id
          controls:
            - ebs_optimized

